---
- name: install initial packages on all boxes
  hosts: all
  remote_user: ansible5
  become: yes

  tasks:
  - name: install all initial packages
    yum:
      name: {{item}}
      state: latest
      with_items:
      - man
      - man-pages
      - mlocate
      - bind-utils
  - name: install ntp packages
    yum:
      name: ntp
      state: latest
  - name: configure ntp
    template:
      src: /ansible5/conf/ntpd.j2
      dest: /etc/ntpd.conf
    notify: restart ntp
  - name: start ntp
    state:
